# Generated by Django 5.1.7 on 2025-03-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceM8', '0007_servicem8log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceM8Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('expires_in', models.IntegerField()),
                ('token_type', models.CharField(max_length=50)),
                ('scope', models.TextField()),
                ('refresh_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
