# Generated by Django 5.1.7 on 2025-03-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceM8', '0008_servicem8token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceM8WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_data', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('logger', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
