# Generated by Django 5.1.7 on 2025-03-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceM8', '0009_servicem8webhooklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceM8Credentials',
        ),
    ]
