# Generated by Django 5.1.7 on 2025-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceM8', '0010_delete_servicem8credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
